CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF BIGINT,
    EMAIL VARCHAR(100),
    "PASSWORD" VARCHAR(100),
    "TYPE" INT,
    BALANCE DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON ACCOUNTS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON ACCOUNTS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    SENDER INT,
    RECIPIENT INT,
    "VALUE" DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (SENDER) REFERENCES ACCOUNTS (ID),
    FOREIGN KEY (RECIPIENT) REFERENCES ACCOUNTS (ID)
);